In [162]:
import pandas as pd
import numpy as np

In [163]:
# smoking data:
smokData = pd.read_csv('data/PA__Percentage_of_Cigarette_Smoking_Among_Adults_Map.csv')

list(smokData.columns.values)
subSmok = smokData[list([smokData.columns[6], smokData.columns[9], smokData.columns[10], smokData.columns[-1]])]
subSmok

     County Name  Percentage/Rate/Ratio       95% CI                 Location
0         Albany                   17.0  (12.8-21.1)  (42.678066, -73.814233)
1       Allegany                   24.6  (19.3-29.9)  (42.226801, -78.020567)
2         Broome                   20.3  (15.4-25.1)  (42.122015, -75.933191)
3    Cattaraugus                   23.5  (19.2-27.8)  (42.224267, -78.606673)
4         Cayuga                   22.1  (17.4-26.8)  (42.940095, -76.560755)
5     Chautauqua                   25.3  (20.4-30.2)  (42.246904, -79.315313)
6        Chemung                   30.0  (24.4-35.7)  (42.116644, -76.812331)
7       Chenango                   23.8  (19.3-28.4)  (42.481798, -75.570013)
8        Clinton                   21.5  (16.1-26.9)  (44.731944, -73.548883)
9       Columbia                   23.1  (18.0-28.2)  (42.276913, -73.682168)
10      Cortland                   22.1  (16.8-27.4)  (42.597101, -76.143291)
11      Delaware                   21.0  (17.0-25.0)  (42.242972, -74.997944)
12      Dutchess                   18.3  (13.9-22.6)  (41.686216, -73.840468)
13          Erie                   25.5  (20.3-30.8)  (42.888143, -78.795544)
14         Essex                   23.0  (18.3-27.8)  (44.166026, -73.685145)
15      Franklin                   30.7  (23.4-38.0)  (44.705699, -74.340621)
16        Fulton                   24.0  (19.7-28.2)   (43.06014, -74.331296)
17       Genesee                   18.0  (14.0-22.0)  (43.000121, -78.172679)
18        Greene                   23.8  (18.0-29.5)  (42.298326, -73.973376)
19      Hamilton                   20.5  (16.1-24.9)  (43.618468, -74.395268)
20      Herkimer                   21.1  (16.7-25.5)  (43.070026, -74.994246)
21     Jefferson                   25.0  (20.2-29.9)  (44.019295, -75.898971)
22         Lewis                   18.9  (14.3-23.6)  (43.785537, -75.446296)
23    Livingston                   16.6  (12.5-20.7)  (42.763754, -77.765392)
24       Madison                   25.2  (20.4-30.0)  (42.986917, -75.720031)
25        Monroe                   19.1  (14.6-23.7)  (43.161748, -77.620143)
26    Montgomery                   21.9  (17.6-26.2)  (42.933637, -74.341972)
27        Nassau                   10.0   (7.2-12.8)  (40.715749, -73.601185)
28       Niagara                   26.2  (21.3-31.1)  (43.134634, -78.856419)
29        Oneida                   24.0  (19.5-28.4)  (43.149482, -75.361773)
..           ...                    ...          ...                      ...
32        Orange                   20.3  (14.8-25.8)  (41.422459, -74.241929)
33       Orleans                   28.9  (23.5-34.4)  (43.248394, -78.218438)
34        Oswego                   24.8  (20.1-29.5)    (43.39123, -76.31133)
35        Otsego                   21.8  (16.7-27.0)  (42.564852, -75.060334)
36        Putnam                   13.0   (9.9-16.1)   (41.41131, -73.717443)
37    Rensselaer                   18.7  (14.6-22.7)   (42.70098, -73.628669)
38      Rockland                    9.5   (6.6-12.5)  (41.127287, -74.017033)
39  St. Lawrence                   24.9  (20.0-29.8)  (44.689468, -75.242045)
40      Saratoga                   17.0  (12.9-21.0)   (43.00894, -73.786779)
41   Schenectady                   17.0  (13.5-20.6)  (42.809233, -73.946838)
42     Schoharie                   23.9  (18.8-29.0)  (42.643426, -74.434606)
43      Schuyler                   22.6  (18.3-27.0)   (42.38593, -76.872032)
44        Seneca                   23.7  (18.7-28.7)   (42.833627, -76.82753)
45       Steuben                   21.1  (17.0-25.3)  (42.270053, -77.324618)
46       Suffolk                   17.5  (12.9-22.1)  (40.820237, -73.119032)
47      Sullivan                   27.9  (22.7-33.0)  (41.705166, -74.711705)
48         Tioga                   21.6  (17.2-26.1)   (42.120252, -76.29595)
49      Tompkins                   13.5   (7.7-19.3)  (42.461024, -76.478784)
50        Ulster                   22.4  (17.8-27.0)  (41.848374, -74.099412)
51        Warren                   20.5  (15.9-25.2)  (43.403024, -73.716044)
52    Washington                   23.2  (17.9-28.4)  (43.289513, -73.454761)
53         Wayne                   19.4  (14.9-23.8)  (43.144336, -77.117995)
54   Westchester                   11.7   (8.1-15.4)  (41.039278, -73.805386)
55       Wyoming                   22.4  (16.2-28.7)  (42.723641, -78.204473)
56         Yates                   17.1  (13.2-20.9)  (42.634338, -77.078311)
57         Bronx                   18.1  (15.4-21.1)   (40.85589, -73.868294)
58         Kings                   16.1  (14.1-18.3)   (40.65642, -73.950691)
59      New York                   15.0  (12.5-18.0)  (40.726966, -74.005966)
60        Queens                   14.6  (12.5-17.0)  (40.749338, -73.789673)
61      Richmond                   19.7  (16.4-23.6)  (40.566763, -74.148102)

[62 rows x 4 columns]

In [164]:
# all-cancer data:
# https://health.data.ny.gov/Health/Community-Health-All-Cancer-Incidence-Age-adjusted/4wxt-6bzs
allCancer = pd.read_csv('data/Community_Health__All_Cancer_Incidence_Age-adjusted_Rate_per_100_000_by_County_Maps__Latest_Data.csv')

allCancer

,County Name,Health Topic Number,Health Topic,Indicator Number,Indicator,Event Count,Average Number of Denominator,Measure Unit,Percent/Rate,Lower Limit of 95% CI,Upper Limit of 95% CI,Data Comments,Quartile,Data Years,Data Source,Mapping Distribution,Location
0,Albany,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,5448,304062,Rate,519.6,NaN,NaN,NaN,507.8 - < 525.5 : Q3,2009-2011,"Cancer Registry Data as of April, 2014",2,"(42.678066, -73.814233)"
1,Allegany,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,856,48899,Rate,498.7,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(42.226801, -78.020567)"
2,Broome,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,3836,200111,Rate,510.0,NaN,NaN,NaN,507.8 - < 525.5 : Q3,2009-2011,"Cancer Registry Data as of April, 2014",2,"(42.122015, -75.933191)"
3,Cattaraugus,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1564,80191,Rate,521.7,NaN,NaN,NaN,507.8 - < 525.5 : Q3,2009-2011,"Cancer Registry Data as of April, 2014",2,"(42.224267, -78.606673)"
4,Cayuga,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1435,79969,Rate,488.2,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(42.940095, -76.560755)"
5,Chautauqua,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,2945,134793,Rate,568.8,NaN,NaN,NaN,525.5 + : Q4,2009-2011,"Cancer Registry Data as of April, 2014",3,"(42.246904, -79.315313)"
6,Chemung,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1806,88840,Rate,547.4,NaN,NaN,NaN,525.5 + : Q4,2009-2011,"Cancer Registry Data as of April, 2014",3,"(42.116644, -76.812331)"
7,Chenango,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1063,50384,Rate,542.8,NaN,NaN,NaN,525.5 + : Q4,2009-2011,"Cancer Registry Data as of April, 2014",3,"(42.481798, -75.570013)"
8,Clinton,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1499,82123,Rate,543.9,NaN,NaN,NaN,525.5 + : Q4,2009-2011,"Cancer Registry Data as of April, 2014",3,"(44.731944, -73.548883)"
9,Columbia,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1289,62864,Rate,486.2,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(42.276913, -73.682168)"
10,Cortland,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,855,49348,Rate,528.6,NaN,NaN,NaN,525.5 + : Q4,2009-2011,"Cancer Registry Data as of April, 2014",3,"(42.597101, -76.143291)"
11,Delaware,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,975,47861,Rate,470.6,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(42.242972, -74.997944)"
12,Dutchess,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,5093,297542,Rate,498.8,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(41.686216, -73.840468)"
13,Erie,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,18693,918704,Rate,551.0,NaN,NaN,NaN,525.5 + : Q4,2009-2011,"Cancer Registry Data as of April, 2014",3,"(42.888143, -78.795544)"
14,Essex,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,762,39325,Rate,463.9,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(44.166026, -73.685145)"
15,Franklin,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,854,51622,Rate,486.1,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(44.705699, -74.340621)"
16,Fulton,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1080,55403,Rate,512.5,NaN,NaN,NaN,507.8 - < 525.5 : Q3,2009-2011,"Cancer Registry Data as of April, 2014",2,"(43.06014, -74.331296)"
17,Genesee,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1218,60002,Rate,546.1,NaN,NaN,NaN,525.5 + : Q4,2009-2011,"Cancer Registry Data as of April, 2014",3,"(43.000121, -78.172679)"
18,Greene,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1016,49162,Rate,509.3,NaN,NaN,NaN,507.8 - < 525.5 : Q3,2009-2011,"Cancer Registry Data as of April, 2014",2,"(42.298326, -73.973376)"
19,Hamilton,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,127,4829,Rate,490.8,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(43.618468, -74.395268)"
20,Herkimer,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1230,64341,Rate,493.1,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(43.070026, -74.994246)"
21,Jefferson,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1682,116538,Rate,508.3,NaN,NaN,NaN,507.8 - < 525.5 : Q3,2009-2011,"Cancer Registry Data as of April, 2014",2,"(44.019295, -75.898971)"
22,Lewis,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,452,27073,Rate,457.4,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(43.785537, -75.446296)"
23,Livingston,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1034,65280,Rate,460.2,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(42.763754, -77.765392)"
24,Madison,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1294,73333,Rate,509.3,NaN,NaN,NaN,507.8 - < 525.5 : Q3,2009-2011,"Cancer Registry Data as of April, 2014",2,"(42.986917, -75.720031)"
25,Monroe,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,13023,744549,Rate,510.4,NaN,NaN,NaN,507.8 - < 525.5 : Q3,2009-2011,"Cancer Registry Data as of April, 2014",2,"(43.161748, -77.620143)"
26,Montgomery,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,983,50059,Rate,507.3,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(42.933637, -74.341972)"
27,Nassau,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,25799,1339186,Rate,522.9,NaN,NaN,NaN,507.8 - < 525.5 : Q3,2009-2011,"Cancer Registry Data as of April, 2014",2,"(40.715749, -73.601185)"
28,Niagara,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,4246,216199,Rate,516.0,NaN,NaN,NaN,507.8 - < 525.5 : Q3,2009-2011,"Cancer Registry Data as of April, 2014",2,"(43.134634, -78.856419)"
29,Oneida,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,4486,234592,Rate,508.3,NaN,NaN,NaN,507.8 - < 525.5 : Q3,2009-2011,"Cancer Registry Data as of April, 2014",2,"(43.149482, -75.361773)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32,Orange,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,5610,373501,Rate,505.5,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(41.422459, -74.241929)"
33,Orleans,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,757,42819,Rate,493.1,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(43.248394, -78.218438)"
34,Oswego,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,2138,122150,Rate,539.7,NaN,NaN,NaN,525.5 + : Q4,2009-2011,"Cancer Registry Data as of April, 2014",3,"(43.39123, -76.31133)"
35,Otsego,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1157,62141,Rate,483.9,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(42.564852, -75.060334)"
36,Putnam,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1727,99772,Rate,516.3,NaN,NaN,NaN,507.8 - < 525.5 : Q3,2009-2011,"Cancer Registry Data as of April, 2014",2,"(41.41131, -73.717443)"
37,Rensselaer,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,2978,159337,Rate,544.7,NaN,NaN,NaN,525.5 + : Q4,2009-2011,"Cancer Registry Data as of April, 2014",3,"(42.70098, -73.628669)"
38,Rockland,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,5187,312110,Rate,507.0,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(41.127287, -74.017033)"
39,St. Lawrence,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1941,111925,Rate,509.0,NaN,NaN,NaN,507.8 - < 525.5 : Q3,2009-2011,"Cancer Registry Data as of April, 2014",2,"(44.689468, -75.242045)"
40,Saratoga,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,3852,219841,Rate,505.3,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(43.00894, -73.786779)"
41,Schenectady,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,2691,154680,Rate,484.6,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(42.809233, -73.946838)"
42,Schoharie,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,611,32682,Rate,498.3,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(42.643426, -74.434606)"
43,Schuyler,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,398,18366,Rate,546.9,NaN,NaN,NaN,525.5 + : Q4,2009-2011,"Cancer Registry Data as of April, 2014",3,"(42.38593, -76.872032)"
44,Seneca,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,639,35230,Rate,489.1,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(42.833627, -76.82753)"
45,Steuben,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1805,98973,Rate,484.4,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(42.270053, -77.324618)"
46,Suffolk,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,27335,1493470,Rate,540.8,NaN,NaN,NaN,525.5 + : Q4,2009-2011,"Cancer Registry Data as of April, 2014",3,"(40.820237, -73.119032)"
47,Sullivan,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1359,77339,Rate,475.6,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(41.705166, -74.711705)"
48,Tioga,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1030,51125,Rate,537.3,NaN,NaN,NaN,525.5 + : Q4,2009-2011,"Cancer Registry Data as of April, 2014",3,"(42.120252, -76.29595)"
49,Tompkins,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1401,101625,Rate,500.6,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(42.461024, -76.478784)"
50,Ulster,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,3256,182520,Rate,479.8,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(41.848374, -74.099412)"
51,Warren,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1395,65749,Rate,520.8,NaN,NaN,NaN,507.8 - < 525.5 : Q3,2009-2011,"Cancer Registry Data as of April, 2014",2,"(43.403024, -73.716044)"
52,Washington,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1315,63188,Rate,564.9,NaN,NaN,NaN,525.5 + : Q4,2009-2011,"Cancer Registry Data as of April, 2014",3,"(43.289513, -73.454761)"
53,Wayne,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1756,93621,Rate,525.5,NaN,NaN,NaN,507.8 - < 525.5 : Q3,2009-2011,"Cancer Registry Data as of April, 2014",2,"(43.144336, -77.117995)"
54,Westchester,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,16591,950128,Rate,493.6,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(41.039278, -73.805386)"
55,Wyoming,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,857,42106,Rate,588.3,NaN,NaN,NaN,525.5 + : Q4,2009-2011,"Cancer Registry Data as of April, 2014",3,"(42.723641, -78.204473)"
56,Yates,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,484,25375,Rate,499.4,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(42.634338, -77.078311)"
57,Bronx,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,17816,1385141,Rate,464.2,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(40.85589, -73.868294)"
58,Kings,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,34142,2509637,Rate,460.2,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(40.65642, -73.950691)"
59,New York,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,24574,1590953,Rate,471.9,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(40.726966, -74.005966)"
60,Queens,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,32106,2232970,Rate,445.1,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(40.749338, -73.789673)"
61,Richmond,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,8053,468942,Rate,522.2,NaN,NaN,NaN,507.8 - < 525.5 : Q3,2009-2011,"Cancer Registry Data as of April, 2014",2,"(40.566763, -74.148102)"

In [183]:
# individual cancer data:
cancerDir = "data/NYSDOH_CancerMapping_Data_2005_2009/"
cancerFile = "NYSDOH_CancerMapping_Data_2005_2009.csv"
indivCancer = pd.read_csv(cancerDir+cancerFile)

indivCancer['countyCode'] = indivCancer['geoid10'].str.slice(2,5)
limited = indivCancer[[indivCancer.columns[-1]] + [indivCancer.columns[0]] + list(indivCancer.columns[1:26])]
ls = list(limited.columns.values)[2:]
byCounty = limited.groupby('countyCode')
aggIndivCan = pd.DataFrame()
for i in ls:
    aggIndivCan[i] = byCounty[i].aggregate(np.sum)
aggIndivCan = aggIndivCan.reset_index()
aggIndivCan

,countyCode,observed_Bladder,observed_Bone,observed_Brain,observed_Breast,observed_Colorectal,observed_Esophagus,observed_Kidney,observed_Larynx,observed_Leukemia,...,observed_Other,observed_Ovary,observed_Pancreas,observed_Prostate,observed_Soft_Tissue,observed_Stomach,observed_Testis,observed_Thyroid,observed_Uterus,observed_Total
0,001,498,14,123,1190,788,106,275,67,257,...,1187,100,227,1278,57,116,43,212,231,8877
1,003,79,3,26,176,153,15,39,12,53,...,190,17,27,193,9,21,4,19,32,1389
2,005,804,76,339,3834,3004,302,846,293,698,...,3641,427,761,4573,196,693,117,634,1025,28438
3,007,328,7,90,817,666,81,188,52,146,...,873,92,128,1031,32,93,25,203,212,6398
4,009,135,4,36,295,279,31,80,28,56,...,338,39,57,359,21,34,17,37,71,2492
5,011,113,8,36,324,217,24,87,26,78,...,329,32,66,398,17,36,11,58,67,2529
6,013,265,3,54,570,382,55,136,34,110,...,606,62,100,864,23,54,14,75,149,4468
7,015,175,7,51,370,268,30,80,33,84,...,522,57,80,389,13,40,9,75,85,3073
8,017,94,4,24,173,156,24,52,13,57,...,257,28,38,210,12,15,9,43,57,1637
9,019,127,6,32,256,232,44,107,27,63,...,285,30,56,333,15,34,14,40,60,2323
10,021,120,2,29,241,195,24,60,15,54,...,298,27,58,325,10,31,15,33,66,2123
11,023,84,2,12,159,131,23,30,11,40,...,205,22,42,231,6,15,6,29,54,1424
12,025,94,3,19,178,165,33,46,16,58,...,237,20,39,214,7,20,5,35,47,1613
13,027,446,10,118,1211,759,87,244,61,209,...,1015,108,212,1014,48,113,46,239,309,7950
14,029,1786,51,401,4131,2634,391,909,259,889,...,4497,398,785,4652,177,396,145,702,868,30639
15,031,72,2,20,160,133,30,39,11,38,...,178,17,38,164,7,18,4,27,51,1314
16,033,79,4,19,153,152,18,42,23,35,...,178,14,41,187,8,10,4,28,42,1385
17,035,111,4,25,214,199,23,71,16,39,...,248,24,48,278,9,19,9,51,59,1862
18,037,90,5,22,251,174,21,62,15,65,...,270,33,38,267,7,27,6,25,63,1853
19,039,107,1,21,220,176,30,42,15,43,...,244,25,52,220,6,24,14,39,52,1745
20,041,9,0,4,22,17,6,4,3,2,...,40,3,3,33,1,3,0,4,3,201
21,043,135,4,27,257,213,31,82,10,46,...,261,25,52,285,4,26,8,55,69,2053
22,045,160,2,37,377,266,39,79,20,99,...,362,44,68,468,28,31,28,55,75,2918
23,047,2052,159,700,7330,6181,487,1638,436,1352,...,7350,826,1565,8215,381,1546,265,1919,2110,55110
24,049,31,1,7,96,78,4,35,11,39,...,114,9,37,120,6,13,2,16,28,808
25,051,104,6,22,255,179,24,53,7,49,...,213,31,26,274,11,20,9,31,47,1761
26,053,122,4,23,269,205,23,57,20,54,...,257,20,50,434,12,26,14,56,51,2167
27,055,1087,43,245,3184,1845,221,738,162,608,...,2915,281,576,3187,137,325,99,446,698,21237
28,057,95,2,18,189,207,18,61,17,42,...,229,17,49,219,12,27,11,36,58,1682
29,059,2259,72,509,6320,3746,348,1450,259,1139,...,6011,664,1169,6281,280,585,203,1272,1423,42162
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32,065,441,8,97,888,685,75,253,71,196,...,1050,111,204,1032,41,109,37,207,193,7464
33,067,717,27,189,1845,1181,148,434,110,433,...,1824,202,375,2441,82,162,76,331,414,14264
34,069,175,4,47,427,232,33,101,19,88,...,457,59,87,473,14,38,21,66,91,3153
35,071,450,20,135,1253,820,96,322,74,259,...,1185,135,208,1308,56,117,69,373,267,9077
36,073,69,2,16,175,132,12,41,13,31,...,152,29,23,143,8,17,6,25,36,1218
37,075,189,7,55,395,338,40,136,41,114,...,433,34,90,514,16,32,17,84,109,3539
38,077,101,3,24,234,180,32,66,14,85,...,265,23,43,216,16,18,12,45,76,1861
39,079,128,6,34,427,217,31,103,22,61,...,362,39,68,388,33,45,15,113,88,2731
40,081,2186,102,681,7194,5523,444,1606,399,1267,...,6544,829,1435,7830,351,1452,226,1559,1848,51634
41,083,243,8,71,626,456,74,188,62,133,...,661,60,96,729,25,56,25,129,163,4994
42,085,654,20,174,1788,1215,115,446,122,353,...,1680,176,357,1777,78,221,75,606,444,13043
43,087,394,16,109,1194,698,89,258,45,235,...,1026,118,199,1484,62,149,52,282,288,8263
44,089,182,3,27,371,336,52,77,37,101,...,470,34,66,459,16,35,19,42,105,3249
45,091,372,8,78,884,552,63,211,56,170,...,856,88,160,922,35,79,48,173,149,6301
46,093,259,7,61,629,464,55,139,36,147,...,660,43,128,554,28,71,25,84,150,4649
47,095,51,1,9,99,100,20,23,7,29,...,141,20,31,115,8,19,7,22,35,986
48,097,23,0,10,69,76,9,13,5,18,...,84,11,12,83,3,3,4,17,19,597
49,099,68,1,21,161,96,11,45,11,39,...,132,12,33,144,5,13,5,18,40,1118
50,101,164,6,39,355,282,36,80,29,74,...,418,38,69,383,15,34,15,44,84,2903
51,103,2233,83,517,6053,4002,459,1476,311,1201,...,6257,625,1189,6321,311,605,236,1439,1332,43863
52,105,124,4,32,280,198,24,73,24,73,...,341,33,64,325,10,39,8,73,82,2361
53,107,92,3,22,208,147,15,62,18,46,...,233,20,41,218,5,16,11,40,41,1579
54,109,127,2,38,314,197,26,50,12,76,...,334,30,55,419,8,26,19,61,91,2318
55,111,276,7,70,750,562,57,164,44,152,...,776,85,155,723,40,56,30,148,185,5515
56,113,145,4,23,300,173,27,66,24,64,...,356,32,46,377,12,27,8,48,91,2374
57,115,118,2,26,269,148,34,67,17,34,...,260,26,49,319,12,27,17,62,71,2048
58,117,156,6,34,344,265,41,78,23,75,...,382,36,73,464,11,34,15,40,68,2766
59,119,1269,51,343,4075,2449,262,810,179,809,...,3753,410,741,4165,188,453,128,873,894,27171
60,121,98,3,26,169,146,14,49,4,45,...,184,24,36,227,8,15,6,28,33,1369
61,123,42,1,14,101,68,9,32,7,23,...,95,11,18,98,10,6,2,14,31,753

In [178]:
print byCounty

<pandas.core.groupby.DataFrameGroupBy object at 0x1074d3990>

In [166]:
# https://www.census.gov/geo/reference/codes/cou.html
# https://www.census.gov/geo/reference/codes/cou.html
heads = ['state', 'sCode', 'cCode', 'county', 'h']
fips = pd.read_csv("data/st36_ny_cou.txt", names=heads, converters={'cCode': lambda x: str(x)})

fips
fips['countyName'] = fips['county'].str.split('County').apply(lambda x: x[0]).str.upper()
fips

   state  sCode cCode               county   h     countyName
0     NY     36   001        Albany County  H1        ALBANY
1     NY     36   003      Allegany County  H1      ALLEGANY
2     NY     36   005         Bronx County  H6         BRONX
3     NY     36   007        Broome County  H1        BROOME
4     NY     36   009   Cattaraugus County  H1   CATTARAUGUS
5     NY     36   011        Cayuga County  H1        CAYUGA
6     NY     36   013    Chautauqua County  H1    CHAUTAUQUA
7     NY     36   015       Chemung County  H1       CHEMUNG
8     NY     36   017      Chenango County  H1      CHENANGO
9     NY     36   019       Clinton County  H1       CLINTON
10    NY     36   021      Columbia County  H1      COLUMBIA
11    NY     36   023      Cortland County  H1      CORTLAND
12    NY     36   025      Delaware County  H1      DELAWARE
13    NY     36   027      Dutchess County  H1      DUTCHESS
14    NY     36   029          Erie County  H1          ERIE
15    NY     36   031         Essex County  H1         ESSEX
16    NY     36   033      Franklin County  H1      FRANKLIN
17    NY     36   035        Fulton County  H1        FULTON
18    NY     36   037       Genesee County  H1       GENESEE
19    NY     36   039        Greene County  H1        GREENE
20    NY     36   041      Hamilton County  H1      HAMILTON
21    NY     36   043      Herkimer County  H1      HERKIMER
22    NY     36   045     Jefferson County  H1     JEFFERSON
23    NY     36   047         Kings County  H6         KINGS
24    NY     36   049         Lewis County  H1         LEWIS
25    NY     36   051    Livingston County  H1    LIVINGSTON
26    NY     36   053       Madison County  H1       MADISON
27    NY     36   055        Monroe County  H1        MONROE
28    NY     36   057    Montgomery County  H1    MONTGOMERY
29    NY     36   059        Nassau County  H1        NASSAU
..   ...    ...   ...                  ...  ..            ...
32    NY     36   065        Oneida County  H1        ONEIDA
33    NY     36   067      Onondaga County  H1      ONONDAGA
34    NY     36   069       Ontario County  H1       ONTARIO
35    NY     36   071        Orange County  H1        ORANGE
36    NY     36   073       Orleans County  H1       ORLEANS
37    NY     36   075        Oswego County  H1        OSWEGO
38    NY     36   077        Otsego County  H1        OTSEGO
39    NY     36   079        Putnam County  H1        PUTNAM
40    NY     36   081        Queens County  H6        QUEENS
41    NY     36   083    Rensselaer County  H1    RENSSELAER
42    NY     36   085      Richmond County  H6      RICHMOND
43    NY     36   087      Rockland County  H1      ROCKLAND
44    NY     36   089  St. Lawrence County  H1  ST. LAWRENCE
45    NY     36   091      Saratoga County  H1      SARATOGA
46    NY     36   093   Schenectady County  H1   SCHENECTADY
47    NY     36   095     Schoharie County  H1     SCHOHARIE
48    NY     36   097      Schuyler County  H1      SCHUYLER
49    NY     36   099        Seneca County  H1        SENECA
50    NY     36   101       Steuben County  H1       STEUBEN
51    NY     36   103       Suffolk County  H1       SUFFOLK
52    NY     36   105      Sullivan County  H1      SULLIVAN
53    NY     36   107         Tioga County  H1         TIOGA
54    NY     36   109      Tompkins County  H1      TOMPKINS
55    NY     36   111        Ulster County  H1        ULSTER
56    NY     36   113        Warren County  H1        WARREN
57    NY     36   115    Washington County  H1    WASHINGTON
58    NY     36   117         Wayne County  H1         WAYNE
59    NY     36   119   Westchester County  H1   WESTCHESTER
60    NY     36   121       Wyoming County  H1       WYOMING
61    NY     36   123         Yates County  H1         YATES

[62 rows x 6 columns]

In [167]:
nyc = {'005': 'Bronx', '047': 'Kings', '061': 'New York', '081': 'Queens', '085': 'Richmond'}

In [168]:
fips['countyName'] = fips['countyName'].str.upper().str.strip()

In [188]:
subSmok['County Name'] = subSmok['County Name'].str.upper().str.strip()
smokMrg = pd.merge(subSmok, fips, left_on = 'County Name', right_on = 'countyName')
smokMrg = smokMrg.drop(['state', 'sCode', 'county', 'h', 'countyName'], 1)

/Users/afair/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [189]:
allCancer['County Name'] = allCancer['County Name'].str.upper().str.strip()
allCanMrg = pd.merge(allCancer, fips, left_on = 'County Name', right_on = 'countyName')
allCanMrg = allCanMrg.drop(['state', 'sCode', 'county', 'h', 'countyName'], 1)

In [190]:
indivCanMrg = pd.merge(aggIndivCan, fips, left_on = 'countyCode', right_on = 'cCode')
indivCanMrg = indivCanMrg.drop(['state', 'sCode', 'cCode', 'county', 'h'], 1)

In [204]:
indivCanMrgPop = pd.merge(indivCanMrg, allCanMrg[['cCode', 'Average Number of Denominator']], left_on = 'countyCode', right_on = 'cCode')