In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('data/PA__Percentage_of_Cigarette_Smoking_Among_Adults_Map.csv')

In [3]:
list(data.columns.values)

['Priority Area Number',
 'Priority Area',
 'Focus Area Number',
 'Focus Area',
 'Indicator Number',
 'Indicator',
 'County Name',
 'Event Count/Rate',
 'Average Number of Denominator/Rate',
 'Percentage/Rate/Ratio',
 '95% CI',
 'Data Comments',
 'Measure Unit',
 'Quartile',
 'Mapping Distribution',
 'Data Years',
 'Data Sources',
 'New York State Baseline',
 '2017 Objective',
 'Objective Region',
 'Location']

In [4]:
subData = data[list([data.columns[6], data.columns[9], data.columns[10], data.columns[-1]])]

In [5]:
subData

     County Name  Percentage/Rate/Ratio       95% CI                 Location
0         Albany                   17.0  (12.8-21.1)  (42.678066, -73.814233)
1       Allegany                   24.6  (19.3-29.9)  (42.226801, -78.020567)
2         Broome                   20.3  (15.4-25.1)  (42.122015, -75.933191)
3    Cattaraugus                   23.5  (19.2-27.8)  (42.224267, -78.606673)
4         Cayuga                   22.1  (17.4-26.8)  (42.940095, -76.560755)
5     Chautauqua                   25.3  (20.4-30.2)  (42.246904, -79.315313)
6        Chemung                   30.0  (24.4-35.7)  (42.116644, -76.812331)
7       Chenango                   23.8  (19.3-28.4)  (42.481798, -75.570013)
8        Clinton                   21.5  (16.1-26.9)  (44.731944, -73.548883)
9       Columbia                   23.1  (18.0-28.2)  (42.276913, -73.682168)
10      Cortland                   22.1  (16.8-27.4)  (42.597101, -76.143291)
11      Delaware                   21.0  (17.0-25.0)  (42.242972, -74.997944)
12      Dutchess                   18.3  (13.9-22.6)  (41.686216, -73.840468)
13          Erie                   25.5  (20.3-30.8)  (42.888143, -78.795544)
14         Essex                   23.0  (18.3-27.8)  (44.166026, -73.685145)
15      Franklin                   30.7  (23.4-38.0)  (44.705699, -74.340621)
16        Fulton                   24.0  (19.7-28.2)   (43.06014, -74.331296)
17       Genesee                   18.0  (14.0-22.0)  (43.000121, -78.172679)
18        Greene                   23.8  (18.0-29.5)  (42.298326, -73.973376)
19      Hamilton                   20.5  (16.1-24.9)  (43.618468, -74.395268)
20      Herkimer                   21.1  (16.7-25.5)  (43.070026, -74.994246)
21     Jefferson                   25.0  (20.2-29.9)  (44.019295, -75.898971)
22         Lewis                   18.9  (14.3-23.6)  (43.785537, -75.446296)
23    Livingston                   16.6  (12.5-20.7)  (42.763754, -77.765392)
24       Madison                   25.2  (20.4-30.0)  (42.986917, -75.720031)
25        Monroe                   19.1  (14.6-23.7)  (43.161748, -77.620143)
26    Montgomery                   21.9  (17.6-26.2)  (42.933637, -74.341972)
27        Nassau                   10.0   (7.2-12.8)  (40.715749, -73.601185)
28       Niagara                   26.2  (21.3-31.1)  (43.134634, -78.856419)
29        Oneida                   24.0  (19.5-28.4)  (43.149482, -75.361773)
..           ...                    ...          ...                      ...
32        Orange                   20.3  (14.8-25.8)  (41.422459, -74.241929)
33       Orleans                   28.9  (23.5-34.4)  (43.248394, -78.218438)
34        Oswego                   24.8  (20.1-29.5)    (43.39123, -76.31133)
35        Otsego                   21.8  (16.7-27.0)  (42.564852, -75.060334)
36        Putnam                   13.0   (9.9-16.1)   (41.41131, -73.717443)
37    Rensselaer                   18.7  (14.6-22.7)   (42.70098, -73.628669)
38      Rockland                    9.5   (6.6-12.5)  (41.127287, -74.017033)
39  St. Lawrence                   24.9  (20.0-29.8)  (44.689468, -75.242045)
40      Saratoga                   17.0  (12.9-21.0)   (43.00894, -73.786779)
41   Schenectady                   17.0  (13.5-20.6)  (42.809233, -73.946838)
42     Schoharie                   23.9  (18.8-29.0)  (42.643426, -74.434606)
43      Schuyler                   22.6  (18.3-27.0)   (42.38593, -76.872032)
44        Seneca                   23.7  (18.7-28.7)   (42.833627, -76.82753)
45       Steuben                   21.1  (17.0-25.3)  (42.270053, -77.324618)
46       Suffolk                   17.5  (12.9-22.1)  (40.820237, -73.119032)
47      Sullivan                   27.9  (22.7-33.0)  (41.705166, -74.711705)
48         Tioga                   21.6  (17.2-26.1)   (42.120252, -76.29595)
49      Tompkins                   13.5   (7.7-19.3)  (42.461024, -76.478784)
50        Ulster                   22.4  (17.8-27.0)  (41.848374, -74.099412)
51        Warren                   20.5  (15.9-25.2)  (43.403024, -73.716044)
52    Washington                   23.2  (17.9-28.4)  (43.289513, -73.454761)
53         Wayne                   19.4  (14.9-23.8)  (43.144336, -77.117995)
54   Westchester                   11.7   (8.1-15.4)  (41.039278, -73.805386)
55       Wyoming                   22.4  (16.2-28.7)  (42.723641, -78.204473)
56         Yates                   17.1  (13.2-20.9)  (42.634338, -77.078311)
57         Bronx                   18.1  (15.4-21.1)   (40.85589, -73.868294)
58         Kings                   16.1  (14.1-18.3)   (40.65642, -73.950691)
59      New York                   15.0  (12.5-18.0)  (40.726966, -74.005966)
60        Queens                   14.6  (12.5-17.0)  (40.749338, -73.789673)
61      Richmond                   19.7  (16.4-23.6)  (40.566763, -74.148102)

[62 rows x 4 columns]

In [6]:
cancerDir = "data/NYSDOH_CancerMapping_Data_2005_2009/"

In [7]:
cancerFile = "NYSDOH_CancerMapping_Data_2005_2009.csv"

In [8]:
cancerDir+cancerFile

'data/NYSDOH_CancerMapping_Data_2005_2009/NYSDOH_CancerMapping_Data_2005_2009.csv'

In [9]:
cancerData = pd.read_csv(cancerDir+cancerFile)

In [10]:
cancerData

,geoid10,observed_Bladder,observed_Bone,observed_Brain,observed_Breast,observed_Colorectal,observed_Esophagus,observed_Kidney,observed_Larynx,observed_Leukemia,...,highlight_Nasal,highlight_Oral,highlight_Ovary,highlight_Pancreas,highlight_Prostate,highlight_Soft_Tissue,highlight_Stomach,highlight_Testis,highlight_Thyroid,highlight_Uterus
0,360010001001,4,0,0,0,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
1,360010001002,1,0,0,2,2,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,360010002001,1,0,1,9,2,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
3,360010002002,0,0,0,3,2,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,360010003001,2,0,0,3,3,0,2,1,2,...,0,0,0,0,0,0,0,0,0,0
5,360010003002,0,0,0,1,7,0,1,2,0,...,0,0,0,0,0,0,0,0,0,0
6,360010003003,7,0,2,2,4,2,3,2,1,...,0,0,0,0,0,0,0,0,0,0
7,360010003004,1,0,1,4,5,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,360010004011,6,0,1,16,11,1,2,0,4,...,0,0,0,0,0,0,0,0,0,0
9,360010004031,4,0,0,7,2,0,1,1,2,...,0,0,0,0,0,0,0,0,0,0
10,360010004032,2,0,0,2,4,1,2,0,1,...,0,0,0,0,0,0,0,0,0,0
11,360010004033,2,0,0,4,2,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
12,360010004034,1,0,1,5,2,1,2,0,1,...,0,0,0,0,0,0,0,0,0,0
13,360010005011,1,0,0,1,2,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,360010005014,1,1,0,1,3,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,360010006003,0,0,2,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
16,360010007001,0,0,1,4,2,0,2,0,1,...,0,0,0,0,0,0,0,0,0,0
17,360010007002,0,0,0,2,3,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
18,360010007003,0,0,0,6,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,360010007004,0,1,1,1,1,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
20,360010008003,0,0,1,2,3,2,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,360010011001,1,0,1,4,7,2,0,1,4,...,0,0,0,0,0,0,0,0,0,0
22,360010014001,0,1,0,3,1,0,2,0,2,...,0,0,0,0,0,0,0,0,0,0
23,360010014002,0,0,0,5,4,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,360010014003,0,0,0,4,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,360010015001,2,0,0,6,2,0,1,1,2,...,0,0,0,0,0,0,0,0,0,0
26,360010016001,0,0,0,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,360010016002,0,0,0,4,1,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
28,360010016003,1,0,0,3,4,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
29,360010016004,1,0,0,5,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13793,361219709003,1,0,0,2,2,0,0,0,0,...,0,0,0,0,0,0,-1,0,-1,0
13794,361219710001,2,1,0,3,6,0,4,0,1,...,0,0,0,0,0,0,-1,0,-1,0
13795,361219710002,1,0,2,4,2,0,0,0,1,...,0,0,0,0,0,0,-1,0,-1,0
13796,361219710003,1,0,0,3,3,1,1,0,0,...,0,0,0,0,0,0,-1,0,-1,0
13797,361219710004,2,0,2,4,2,0,1,0,2,...,0,0,0,0,0,0,-1,0,-1,0
13798,361219711001,6,0,0,2,3,0,4,0,0,...,0,0,0,0,0,0,-1,0,-1,0
13799,361219711002,5,0,1,4,5,0,1,0,2,...,0,0,0,0,0,0,-1,0,-1,0
13800,361219711003,3,0,1,5,2,0,2,0,0,...,0,0,0,0,0,0,-1,0,-1,0
13801,36121DOH0001,4,0,0,6,3,1,4,0,2,...,0,0,0,0,0,0,-1,0,-1,0
13802,361231501001,3,0,1,6,2,1,4,1,0,...,0,0,0,0,0,0,-1,0,0,0
13803,361231501002,1,0,0,2,3,1,0,0,0,...,0,0,0,0,0,0,-1,0,0,0
13804,361231501003,2,0,0,2,2,0,0,1,1,...,0,0,0,0,0,0,-1,0,0,0
13805,361231501004,3,0,0,4,1,0,0,0,1,...,0,0,0,0,0,0,-1,0,0,0
13806,361231501005,2,0,0,2,3,0,0,0,0,...,0,0,0,0,0,0,-1,0,0,0
13807,361231501006,1,0,3,5,4,1,1,0,1,...,0,0,0,0,0,0,-1,0,-1,0
13808,361231502001,2,0,3,12,7,3,4,0,3,...,0,0,0,0,0,0,-1,0,-1,0
13809,361231502002,0,0,1,5,1,0,2,0,1,...,0,0,0,0,0,0,-1,0,-1,0
13810,361231502003,3,0,0,5,5,1,1,1,0,...,0,0,0,0,0,0,-1,0,-1,0
13811,361231503001,2,0,0,6,4,0,5,0,1,...,0,0,0,0,0,0,-1,0,-1,0
13812,361231503002,0,0,2,3,6,1,5,0,1,...,0,0,0,0,0,0,-1,0,-1,0
13813,361231503003,2,0,0,5,5,0,1,3,1,...,0,0,0,0,0,0,-1,0,-1,0
13814,361231503004,2,0,0,7,4,0,1,0,2,...,0,0,0,0,0,0,-1,0,-1,0
13815,361231504001,6,0,0,6,2,0,1,0,1,...,0,0,0,0,0,0,-1,0,-1,0
13816,361231504002,0,1,2,9,1,0,1,0,1,...,0,0,0,0,0,0,-1,0,-1,0
13817,361231504003,4,0,1,2,1,1,0,0,2,...,0,0,0,0,0,0,-1,0,-1,0
13818,361231504004,1,0,1,3,2,0,0,0,1,...,0,0,0,0,0,0,-1,0,-1,0
13819,361231505001,2,0,0,4,6,0,1,0,3,...,0,0,0,0,0,0,-1,0,-1,0
13820,361231505002,3,0,0,6,2,0,2,1,2,...,0,0,0,0,0,0,-1,0,-1,0
13821,361231505003,3,0,0,5,7,0,1,0,1,...,0,0,0,0,0,0,-1,0,-1,0
13822,361231505004,0,0,0,2,0,0,2,0,0,...,0,0,0,0,0,0,-1,0,-1,0

In [11]:
# https://health.data.ny.gov/Health/Community-Health-All-Cancer-Incidence-Age-adjusted/4wxt-6bzs
c = pd.read_csv('data/Community_Health__All_Cancer_Incidence_Age-adjusted_Rate_per_100_000_by_County_Maps__Latest_Data.csv')

In [12]:
c

,County Name,Health Topic Number,Health Topic,Indicator Number,Indicator,Event Count,Average Number of Denominator,Measure Unit,Percent/Rate,Lower Limit of 95% CI,Upper Limit of 95% CI,Data Comments,Quartile,Data Years,Data Source,Mapping Distribution,Location
0,Albany,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,5448,304062,Rate,519.6,NaN,NaN,NaN,507.8 - < 525.5 : Q3,2009-2011,"Cancer Registry Data as of April, 2014",2,"(42.678066, -73.814233)"
1,Allegany,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,856,48899,Rate,498.7,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(42.226801, -78.020567)"
2,Broome,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,3836,200111,Rate,510.0,NaN,NaN,NaN,507.8 - < 525.5 : Q3,2009-2011,"Cancer Registry Data as of April, 2014",2,"(42.122015, -75.933191)"
3,Cattaraugus,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1564,80191,Rate,521.7,NaN,NaN,NaN,507.8 - < 525.5 : Q3,2009-2011,"Cancer Registry Data as of April, 2014",2,"(42.224267, -78.606673)"
4,Cayuga,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1435,79969,Rate,488.2,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(42.940095, -76.560755)"
5,Chautauqua,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,2945,134793,Rate,568.8,NaN,NaN,NaN,525.5 + : Q4,2009-2011,"Cancer Registry Data as of April, 2014",3,"(42.246904, -79.315313)"
6,Chemung,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1806,88840,Rate,547.4,NaN,NaN,NaN,525.5 + : Q4,2009-2011,"Cancer Registry Data as of April, 2014",3,"(42.116644, -76.812331)"
7,Chenango,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1063,50384,Rate,542.8,NaN,NaN,NaN,525.5 + : Q4,2009-2011,"Cancer Registry Data as of April, 2014",3,"(42.481798, -75.570013)"
8,Clinton,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1499,82123,Rate,543.9,NaN,NaN,NaN,525.5 + : Q4,2009-2011,"Cancer Registry Data as of April, 2014",3,"(44.731944, -73.548883)"
9,Columbia,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1289,62864,Rate,486.2,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(42.276913, -73.682168)"
10,Cortland,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,855,49348,Rate,528.6,NaN,NaN,NaN,525.5 + : Q4,2009-2011,"Cancer Registry Data as of April, 2014",3,"(42.597101, -76.143291)"
11,Delaware,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,975,47861,Rate,470.6,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(42.242972, -74.997944)"
12,Dutchess,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,5093,297542,Rate,498.8,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(41.686216, -73.840468)"
13,Erie,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,18693,918704,Rate,551.0,NaN,NaN,NaN,525.5 + : Q4,2009-2011,"Cancer Registry Data as of April, 2014",3,"(42.888143, -78.795544)"
14,Essex,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,762,39325,Rate,463.9,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(44.166026, -73.685145)"
15,Franklin,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,854,51622,Rate,486.1,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(44.705699, -74.340621)"
16,Fulton,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1080,55403,Rate,512.5,NaN,NaN,NaN,507.8 - < 525.5 : Q3,2009-2011,"Cancer Registry Data as of April, 2014",2,"(43.06014, -74.331296)"
17,Genesee,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1218,60002,Rate,546.1,NaN,NaN,NaN,525.5 + : Q4,2009-2011,"Cancer Registry Data as of April, 2014",3,"(43.000121, -78.172679)"
18,Greene,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1016,49162,Rate,509.3,NaN,NaN,NaN,507.8 - < 525.5 : Q3,2009-2011,"Cancer Registry Data as of April, 2014",2,"(42.298326, -73.973376)"
19,Hamilton,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,127,4829,Rate,490.8,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(43.618468, -74.395268)"
20,Herkimer,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1230,64341,Rate,493.1,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(43.070026, -74.994246)"
21,Jefferson,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1682,116538,Rate,508.3,NaN,NaN,NaN,507.8 - < 525.5 : Q3,2009-2011,"Cancer Registry Data as of April, 2014",2,"(44.019295, -75.898971)"
22,Lewis,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,452,27073,Rate,457.4,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(43.785537, -75.446296)"
23,Livingston,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1034,65280,Rate,460.2,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(42.763754, -77.765392)"
24,Madison,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1294,73333,Rate,509.3,NaN,NaN,NaN,507.8 - < 525.5 : Q3,2009-2011,"Cancer Registry Data as of April, 2014",2,"(42.986917, -75.720031)"
25,Monroe,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,13023,744549,Rate,510.4,NaN,NaN,NaN,507.8 - < 525.5 : Q3,2009-2011,"Cancer Registry Data as of April, 2014",2,"(43.161748, -77.620143)"
26,Montgomery,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,983,50059,Rate,507.3,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(42.933637, -74.341972)"
27,Nassau,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,25799,1339186,Rate,522.9,NaN,NaN,NaN,507.8 - < 525.5 : Q3,2009-2011,"Cancer Registry Data as of April, 2014",2,"(40.715749, -73.601185)"
28,Niagara,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,4246,216199,Rate,516.0,NaN,NaN,NaN,507.8 - < 525.5 : Q3,2009-2011,"Cancer Registry Data as of April, 2014",2,"(43.134634, -78.856419)"
29,Oneida,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,4486,234592,Rate,508.3,NaN,NaN,NaN,507.8 - < 525.5 : Q3,2009-2011,"Cancer Registry Data as of April, 2014",2,"(43.149482, -75.361773)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32,Orange,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,5610,373501,Rate,505.5,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(41.422459, -74.241929)"
33,Orleans,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,757,42819,Rate,493.1,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(43.248394, -78.218438)"
34,Oswego,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,2138,122150,Rate,539.7,NaN,NaN,NaN,525.5 + : Q4,2009-2011,"Cancer Registry Data as of April, 2014",3,"(43.39123, -76.31133)"
35,Otsego,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1157,62141,Rate,483.9,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(42.564852, -75.060334)"
36,Putnam,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1727,99772,Rate,516.3,NaN,NaN,NaN,507.8 - < 525.5 : Q3,2009-2011,"Cancer Registry Data as of April, 2014",2,"(41.41131, -73.717443)"
37,Rensselaer,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,2978,159337,Rate,544.7,NaN,NaN,NaN,525.5 + : Q4,2009-2011,"Cancer Registry Data as of April, 2014",3,"(42.70098, -73.628669)"
38,Rockland,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,5187,312110,Rate,507.0,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(41.127287, -74.017033)"
39,St. Lawrence,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1941,111925,Rate,509.0,NaN,NaN,NaN,507.8 - < 525.5 : Q3,2009-2011,"Cancer Registry Data as of April, 2014",2,"(44.689468, -75.242045)"
40,Saratoga,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,3852,219841,Rate,505.3,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(43.00894, -73.786779)"
41,Schenectady,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,2691,154680,Rate,484.6,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(42.809233, -73.946838)"
42,Schoharie,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,611,32682,Rate,498.3,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(42.643426, -74.434606)"
43,Schuyler,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,398,18366,Rate,546.9,NaN,NaN,NaN,525.5 + : Q4,2009-2011,"Cancer Registry Data as of April, 2014",3,"(42.38593, -76.872032)"
44,Seneca,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,639,35230,Rate,489.1,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(42.833627, -76.82753)"
45,Steuben,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1805,98973,Rate,484.4,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(42.270053, -77.324618)"
46,Suffolk,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,27335,1493470,Rate,540.8,NaN,NaN,NaN,525.5 + : Q4,2009-2011,"Cancer Registry Data as of April, 2014",3,"(40.820237, -73.119032)"
47,Sullivan,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1359,77339,Rate,475.6,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(41.705166, -74.711705)"
48,Tioga,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1030,51125,Rate,537.3,NaN,NaN,NaN,525.5 + : Q4,2009-2011,"Cancer Registry Data as of April, 2014",3,"(42.120252, -76.29595)"
49,Tompkins,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1401,101625,Rate,500.6,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(42.461024, -76.478784)"
50,Ulster,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,3256,182520,Rate,479.8,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(41.848374, -74.099412)"
51,Warren,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1395,65749,Rate,520.8,NaN,NaN,NaN,507.8 - < 525.5 : Q3,2009-2011,"Cancer Registry Data as of April, 2014",2,"(43.403024, -73.716044)"
52,Washington,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1315,63188,Rate,564.9,NaN,NaN,NaN,525.5 + : Q4,2009-2011,"Cancer Registry Data as of April, 2014",3,"(43.289513, -73.454761)"
53,Wayne,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,1756,93621,Rate,525.5,NaN,NaN,NaN,507.8 - < 525.5 : Q3,2009-2011,"Cancer Registry Data as of April, 2014",2,"(43.144336, -77.117995)"
54,Westchester,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,16591,950128,Rate,493.6,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(41.039278, -73.805386)"
55,Wyoming,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,857,42106,Rate,588.3,NaN,NaN,NaN,525.5 + : Q4,2009-2011,"Cancer Registry Data as of April, 2014",3,"(42.723641, -78.204473)"
56,Yates,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,484,25375,Rate,499.4,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(42.634338, -77.078311)"
57,Bronx,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,17816,1385141,Rate,464.2,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(40.85589, -73.868294)"
58,Kings,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,34142,2509637,Rate,460.2,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(40.65642, -73.950691)"
59,New York,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,24574,1590953,Rate,471.9,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(40.726966, -74.005966)"
60,Queens,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,32106,2232970,Rate,445.1,NaN,NaN,NaN,0 - < 507.8 : Q1 & Q2,2009-2011,"Cancer Registry Data as of April, 2014",1,"(40.749338, -73.789673)"
61,Richmond,1,Cancer Indicators,g1a,Age-adjusted all cancer incidence rate per 100...,8053,468942,Rate,522.2,NaN,NaN,NaN,507.8 - < 525.5 : Q3,2009-2011,"Cancer Registry Data as of April, 2014",2,"(40.566763, -74.148102)"

In [17]:
cancerData['countyCode'] = cancerData['geoid10'].str.slice(2,5)

In [18]:
cancerData

,geoid10,observed_Bladder,observed_Bone,observed_Brain,observed_Breast,observed_Colorectal,observed_Esophagus,observed_Kidney,observed_Larynx,observed_Leukemia,...,highlight_Oral,highlight_Ovary,highlight_Pancreas,highlight_Prostate,highlight_Soft_Tissue,highlight_Stomach,highlight_Testis,highlight_Thyroid,highlight_Uterus,countyCode
0,360010001001,4,0,0,0,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,001
1,360010001002,1,0,0,2,2,1,0,0,0,...,0,0,0,0,0,0,0,0,0,001
2,360010002001,1,0,1,9,2,0,0,1,1,...,0,0,0,0,0,0,0,0,0,001
3,360010002002,0,0,0,3,2,0,1,0,0,...,0,0,0,0,0,0,0,0,0,001
4,360010003001,2,0,0,3,3,0,2,1,2,...,0,0,0,0,0,0,0,0,0,001
5,360010003002,0,0,0,1,7,0,1,2,0,...,0,0,0,0,0,0,0,0,0,001
6,360010003003,7,0,2,2,4,2,3,2,1,...,0,0,0,0,0,0,0,0,0,001
7,360010003004,1,0,1,4,5,1,0,0,0,...,0,0,0,0,0,0,0,0,0,001
8,360010004011,6,0,1,16,11,1,2,0,4,...,0,0,0,0,0,0,0,0,0,001
9,360010004031,4,0,0,7,2,0,1,1,2,...,0,0,0,0,0,0,0,0,0,001
10,360010004032,2,0,0,2,4,1,2,0,1,...,0,0,0,0,0,0,0,0,0,001
11,360010004033,2,0,0,4,2,0,0,1,0,...,0,0,0,0,0,0,0,0,0,001
12,360010004034,1,0,1,5,2,1,2,0,1,...,0,0,0,0,0,0,0,0,0,001
13,360010005011,1,0,0,1,2,1,0,0,0,...,0,0,0,0,0,0,0,0,0,001
14,360010005014,1,1,0,1,3,0,0,0,0,...,0,0,0,0,0,0,0,0,0,001
15,360010006003,0,0,2,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,001
16,360010007001,0,0,1,4,2,0,2,0,1,...,0,0,0,0,0,0,0,0,0,001
17,360010007002,0,0,0,2,3,1,0,1,0,...,0,0,0,0,0,0,0,0,0,001
18,360010007003,0,0,0,6,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,001
19,360010007004,0,1,1,1,1,0,1,1,0,...,0,0,0,0,0,0,0,0,0,001
20,360010008003,0,0,1,2,3,2,0,0,0,...,0,0,0,0,0,0,0,0,0,001
21,360010011001,1,0,1,4,7,2,0,1,4,...,0,0,0,0,0,0,0,0,0,001
22,360010014001,0,1,0,3,1,0,2,0,2,...,0,0,0,0,0,0,0,0,0,001
23,360010014002,0,0,0,5,4,0,0,0,0,...,0,0,0,0,0,0,0,0,0,001
24,360010014003,0,0,0,4,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,001
25,360010015001,2,0,0,6,2,0,1,1,2,...,0,0,0,0,0,0,0,0,0,001
26,360010016001,0,0,0,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,001
27,360010016002,0,0,0,4,1,1,0,0,1,...,0,0,0,0,0,0,0,0,0,001
28,360010016003,1,0,0,3,4,0,0,1,0,...,0,0,0,0,0,0,0,0,0,001
29,360010016004,1,0,0,5,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13793,361219709003,1,0,0,2,2,0,0,0,0,...,0,0,0,0,0,-1,0,-1,0,121
13794,361219710001,2,1,0,3,6,0,4,0,1,...,0,0,0,0,0,-1,0,-1,0,121
13795,361219710002,1,0,2,4,2,0,0,0,1,...,0,0,0,0,0,-1,0,-1,0,121
13796,361219710003,1,0,0,3,3,1,1,0,0,...,0,0,0,0,0,-1,0,-1,0,121
13797,361219710004,2,0,2,4,2,0,1,0,2,...,0,0,0,0,0,-1,0,-1,0,121
13798,361219711001,6,0,0,2,3,0,4,0,0,...,0,0,0,0,0,-1,0,-1,0,121
13799,361219711002,5,0,1,4,5,0,1,0,2,...,0,0,0,0,0,-1,0,-1,0,121
13800,361219711003,3,0,1,5,2,0,2,0,0,...,0,0,0,0,0,-1,0,-1,0,121
13801,36121DOH0001,4,0,0,6,3,1,4,0,2,...,0,0,0,0,0,-1,0,-1,0,121
13802,361231501001,3,0,1,6,2,1,4,1,0,...,0,0,0,0,0,-1,0,0,0,123
13803,361231501002,1,0,0,2,3,1,0,0,0,...,0,0,0,0,0,-1,0,0,0,123
13804,361231501003,2,0,0,2,2,0,0,1,1,...,0,0,0,0,0,-1,0,0,0,123
13805,361231501004,3,0,0,4,1,0,0,0,1,...,0,0,0,0,0,-1,0,0,0,123
13806,361231501005,2,0,0,2,3,0,0,0,0,...,0,0,0,0,0,-1,0,0,0,123
13807,361231501006,1,0,3,5,4,1,1,0,1,...,0,0,0,0,0,-1,0,-1,0,123
13808,361231502001,2,0,3,12,7,3,4,0,3,...,0,0,0,0,0,-1,0,-1,0,123
13809,361231502002,0,0,1,5,1,0,2,0,1,...,0,0,0,0,0,-1,0,-1,0,123
13810,361231502003,3,0,0,5,5,1,1,1,0,...,0,0,0,0,0,-1,0,-1,0,123
13811,361231503001,2,0,0,6,4,0,5,0,1,...,0,0,0,0,0,-1,0,-1,0,123
13812,361231503002,0,0,2,3,6,1,5,0,1,...,0,0,0,0,0,-1,0,-1,0,123
13813,361231503003,2,0,0,5,5,0,1,3,1,...,0,0,0,0,0,-1,0,-1,0,123
13814,361231503004,2,0,0,7,4,0,1,0,2,...,0,0,0,0,0,-1,0,-1,0,123
13815,361231504001,6,0,0,6,2,0,1,0,1,...,0,0,0,0,0,-1,0,-1,0,123
13816,361231504002,0,1,2,9,1,0,1,0,1,...,0,0,0,0,0,-1,0,-1,0,123
13817,361231504003,4,0,1,2,1,1,0,0,2,...,0,0,0,0,0,-1,0,-1,0,123
13818,361231504004,1,0,1,3,2,0,0,0,1,...,0,0,0,0,0,-1,0,-1,0,123
13819,361231505001,2,0,0,4,6,0,1,0,3,...,0,0,0,0,0,-1,0,-1,0,123
13820,361231505002,3,0,0,6,2,0,2,1,2,...,0,0,0,0,0,-1,0,-1,0,123
13821,361231505003,3,0,0,5,7,0,1,0,1,...,0,0,0,0,0,-1,0,-1,0,123
13822,361231505004,0,0,0,2,0,0,2,0,0,...,0,0,0,0,0,-1,0,-1,0,123

In [37]:
list(enumerate(cancerData.columns.values))

[(0, 'geoid10'),
 (1, 'observed_Bladder'),
 (2, 'observed_Bone'),
 (3, 'observed_Brain'),
 (4, 'observed_Breast'),
 (5, 'observed_Colorectal'),
 (6, 'observed_Esophagus'),
 (7, 'observed_Kidney'),
 (8, 'observed_Larynx'),
 (9, 'observed_Leukemia'),
 (10, 'observed_Liver'),
 (11, 'observed_Lung'),
 (12, 'observed_Mesothelioma'),
 (13, 'observed_NHL'),
 (14, 'observed_Nasal'),
 (15, 'observed_Oral'),
 (16, 'observed_Other'),
 (17, 'observed_Ovary'),
 (18, 'observed_Pancreas'),
 (19, 'observed_Prostate'),
 (20, 'observed_Soft_Tissue'),
 (21, 'observed_Stomach'),
 (22, 'observed_Testis'),
 (23, 'observed_Thyroid'),
 (24, 'observed_Uterus'),
 (25, 'observed_Total'),
 (26, 'expected_Bladder'),
 (27, 'expected_Bone'),
 (28, 'expected_Brain'),
 (29, 'expected_Breast'),
 (30, 'expected_Colorectal'),
 (31, 'expected_Esophagus'),
 (32, 'expected_Kidney'),
 (33, 'expected_Larynx'),
 (34, 'expected_Leukemia'),
 (35, 'expected_Liver'),
 (36, 'expected_Lung'),
 (37, 'expected_Mesothelioma'),
 (38, 'expected_NHL'),
 (39, 'expected_Nasal'),
 (40, 'expected_Oral'),
 (41, 'expected_Other'),
 (42, 'expected_Ovary'),
 (43, 'expected_Pancreas'),
 (44, 'expected_Prostate'),
 (45, 'expected_Soft_Tissue'),
 (46, 'expected_Stomach'),
 (47, 'expected_Testis'),
 (48, 'expected_Thyroid'),
 (49, 'expected_Uterus'),
 (50, 'expected_Total'),
 (51, 'highlight_Bladder'),
 (52, 'highlight_Bone'),
 (53, 'highlight_Brain'),
 (54, 'highlight_Breast'),
 (55, 'highlight_Colorectal'),
 (56, 'highlight_Esophagus'),
 (57, 'highlight_Kidney'),
 (58, 'highlight_Larynx'),
 (59, 'highlight_Leukemia'),
 (60, 'highlight_Liver'),
 (61, 'highlight_Lung'),
 (62, 'highlight_Mesothelioma'),
 (63, 'highlight_NHL'),
 (64, 'highlight_Nasal'),
 (65, 'highlight_Oral'),
 (66, 'highlight_Ovary'),
 (67, 'highlight_Pancreas'),
 (68, 'highlight_Prostate'),
 (69, 'highlight_Soft_Tissue'),
 (70, 'highlight_Stomach'),
 (71, 'highlight_Testis'),
 (72, 'highlight_Thyroid'),
 (73, 'highlight_Uterus'),
 (74, 'countyCode')]

In [20]:
xwalkFile = 'NYSDOH_CancerMapping_Crosswalk_2005_2009.csv'

In [21]:
xwalk = pd.read_csv(cancerDir + xwalkFile)

In [22]:
xwalk

            geoid10     dohregion
0      360010001001  360010001001
1      360010001002  360010001002
2      360010002001  360010002001
3      360010002002  360010002002
4      360010003001  360010003001
5      360010003002  360010003002
6      360010003003  360010003003
7      360010003004  360010003004
8      360010004011  360010004011
9      360010004031  360010004031
10     360010004032  360010004032
11     360010004033  360010004033
12     360010004034  360010004034
13     360010005011  360010005011
14     360010005014  360010005014
15     360010006003  360010006003
16     360010007001  360010007001
17     360010007002  360010007002
18     360010007003  360010007003
19     360010007004  360010007004
20     360010008003  360010008003
21     360010011001  360010011001
22     360010014001  360010014001
23     360010014002  360010014002
24     360010014003  360010014003
25     360010015001  360010015001
26     360010016001  360010016001
27     360010016002  360010016002
28     360010016003  360010016003
29     360010016004  360010016004
...             ...           ...
15164  360670018001  36067DOH0004
15165  360670018002  36067DOH0004
15166  360810409003  36081DOH0089
15167  360810409004  36081DOH0089
15168  361190011011  36119DOH0010
15169  361190011012  36119DOH0010
15170  360290046012  36029DOH0016
15171  360290046014  36029DOH0016
15172  360050229011  36005DOH0102
15173  360050229013  36005DOH0102
15174  360050397001  36005DOH0170
15175  360050397002  36005DOH0170
15176  360550095001  36055DOH0053
15177  360550095003  36055DOH0053
15178  360610172001  36061DOH0053
15179  360610172005  36061DOH0053
15180  360810469003  36081DOH0097
15181  360810469004  36081DOH0097
15182  360810485001  36081DOH0099
15183  360810485002  36081DOH0099
15184  361090002001  36109DOH0001
15185  361090002002  36109DOH0001
15186  361090002003  36109DOH0001
15187  361090013002  36109DOH0001
15188  361090013004  36109DOH0001
15189  361090013005  36109DOH0001
15190  361090003001  36109DOH0002
15191  361090004001  36109DOH0002
15192  360050236001  36005DOH0108
15193  360050236002  36005DOH0108

[15194 rows x 2 columns]

In [23]:
byCounty = cancerData.groupby('countyCode')

In [24]:
byCounty

In [29]:
byCounty['observed_Bladder'].aggregate(np.sum)

countyCode
001     498
003      79
005     804
007     328
009     135
011     113
013     265
015     175
017      94
019     127
021     120
023      84
025      94
027     446
029    1786
031      72
033      79
035     111
037      90
039     107
041       9
043     135
045     160
047    2052
049      31
051     104
053     122
055    1087
057      95
059    2259
       ...
065     441
067     717
069     175
071     450
073      69
075     189
077     101
079     128
081    2186
083     243
085     654
087     394
089     182
091     372
093     259
095      51
097      23
099      68
101     164
103    2233
105     124
107      92
109     127
111     276
113     145
115     118
117     156
119    1269
121      98
123      42
Name: observed_Bladder, dtype: int64

In [28]:
import numpy as np

In [60]:
# analysis = cancerData[list(cancerData.columns[0:26]) + [cancerData.columns[-1]]]
analysis = cancerData[[cancerData.columns[-1]] + [cancerData.columns[0]] + list(cancerData.columns[1:26])]

In [61]:
analysis

,countyCode,geoid10,observed_Bladder,observed_Bone,observed_Brain,observed_Breast,observed_Colorectal,observed_Esophagus,observed_Kidney,observed_Larynx,...,observed_Other,observed_Ovary,observed_Pancreas,observed_Prostate,observed_Soft_Tissue,observed_Stomach,observed_Testis,observed_Thyroid,observed_Uterus,observed_Total
0,001,360010001001,4,0,0,0,1,0,1,0,...,6,0,0,5,0,1,1,0,1,31
1,001,360010001002,1,0,0,2,2,1,0,0,...,5,1,0,3,0,1,0,0,0,22
2,001,360010002001,1,0,1,9,2,0,0,1,...,4,0,1,6,0,1,0,0,3,51
3,001,360010002002,0,0,0,3,2,0,1,0,...,5,0,0,2,0,1,0,0,0,20
4,001,360010003001,2,0,0,3,3,0,2,1,...,2,0,0,8,0,0,1,2,0,32
5,001,360010003002,0,0,0,1,7,0,1,2,...,7,1,1,4,0,0,0,1,1,38
6,001,360010003003,7,0,2,2,4,2,3,2,...,10,3,1,12,1,2,0,1,0,71
7,001,360010003004,1,0,1,4,5,1,0,0,...,3,1,1,5,0,1,0,0,2,32
8,001,360010004011,6,0,1,16,11,1,2,0,...,23,2,6,9,2,1,0,0,6,108
9,001,360010004031,4,0,0,7,2,0,1,1,...,6,0,0,4,1,1,0,0,2,42
10,001,360010004032,2,0,0,2,4,1,2,0,...,7,0,1,8,0,0,1,4,1,43
11,001,360010004033,2,0,0,4,2,0,0,1,...,3,0,0,5,0,1,1,0,0,25
12,001,360010004034,1,0,1,5,2,1,2,0,...,4,2,1,11,0,0,1,1,0,41
13,001,360010005011,1,0,0,1,2,1,0,0,...,2,0,1,1,0,0,0,0,2,13
14,001,360010005014,1,1,0,1,3,0,0,0,...,4,0,0,4,0,1,0,0,2,25
15,001,360010006003,0,0,2,0,1,0,0,0,...,2,1,0,2,0,0,0,0,0,19
16,001,360010007001,0,0,1,4,2,0,2,0,...,2,0,0,4,0,0,0,3,1,25
17,001,360010007002,0,0,0,2,3,1,0,1,...,4,0,0,1,0,1,0,0,0,17
18,001,360010007003,0,0,0,6,4,1,0,0,...,3,0,1,5,0,1,0,0,0,29
19,001,360010007004,0,1,1,1,1,0,1,1,...,6,0,1,3,0,0,0,1,0,20
20,001,360010008003,0,0,1,2,3,2,0,0,...,2,0,1,1,0,0,0,0,0,16
21,001,360010011001,1,0,1,4,7,2,0,1,...,9,0,2,10,0,1,0,2,1,69
22,001,360010014001,0,1,0,3,1,0,2,0,...,3,0,1,2,0,2,1,1,0,23
23,001,360010014002,0,0,0,5,4,0,0,0,...,3,1,2,3,0,0,0,0,0,20
24,001,360010014003,0,0,0,4,0,1,0,0,...,2,0,0,2,0,1,0,1,1,16
25,001,360010015001,2,0,0,6,2,0,1,1,...,7,0,1,2,1,0,0,0,1,33
26,001,360010016001,0,0,0,0,1,1,0,0,...,4,1,0,2,0,0,0,1,0,13
27,001,360010016002,0,0,0,4,1,1,0,0,...,1,0,2,4,0,0,0,0,0,17
28,001,360010016003,1,0,0,3,4,0,0,1,...,1,0,1,2,0,0,0,1,0,20
29,001,360010016004,1,0,0,5,1,0,0,1,...,5,1,1,4,0,0,0,0,0,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13793,121,361219709003,1,0,0,2,2,0,0,0,...,4,0,0,6,0,0,0,1,2,26
13794,121,361219710001,2,1,0,3,6,0,4,0,...,5,0,4,5,0,0,0,0,0,39
13795,121,361219710002,1,0,2,4,2,0,0,0,...,2,0,2,7,0,0,1,0,0,25
13796,121,361219710003,1,0,0,3,3,1,1,0,...,6,0,0,8,1,0,0,2,0,29
13797,121,361219710004,2,0,2,4,2,0,1,0,...,6,3,0,7,1,0,0,0,1,39
13798,121,361219711001,6,0,0,2,3,0,4,0,...,0,0,0,3,0,0,0,2,1,24
13799,121,361219711002,5,0,1,4,5,0,1,0,...,1,0,0,4,0,1,0,0,0,35
13800,121,361219711003,3,0,1,5,2,0,2,0,...,4,0,0,8,0,0,0,1,0,29
13801,121,36121DOH0001,4,0,0,6,3,1,4,0,...,2,1,0,5,0,1,0,1,2,36
13802,123,361231501001,3,0,1,6,2,1,4,1,...,5,0,1,0,0,1,0,1,3,35
13803,123,361231501002,1,0,0,2,3,1,0,0,...,5,3,1,4,0,0,0,1,0,25
13804,123,361231501003,2,0,0,2,2,0,0,1,...,3,1,1,3,1,0,0,0,1,24
13805,123,361231501004,3,0,0,4,1,0,0,0,...,3,0,1,3,0,0,0,0,1,22
13806,123,361231501005,2,0,0,2,3,0,0,0,...,3,0,1,5,1,0,0,1,2,25
13807,123,361231501006,1,0,3,5,4,1,1,0,...,5,0,0,4,0,1,0,1,1,38
13808,123,361231502001,2,0,3,12,7,3,4,0,...,15,2,1,8,1,0,0,2,6,97
13809,123,361231502002,0,0,1,5,1,0,2,0,...,3,1,1,8,1,0,0,0,1,32
13810,123,361231502003,3,0,0,5,5,1,1,1,...,5,0,2,5,0,2,0,1,2,44
13811,123,361231503001,2,0,0,6,4,0,5,0,...,5,1,0,4,2,0,0,1,2,48
13812,123,361231503002,0,0,2,3,6,1,5,0,...,6,0,1,0,1,0,0,0,3,40
13813,123,361231503003,2,0,0,5,5,0,1,3,...,5,0,0,4,0,0,0,1,1,36
13814,123,361231503004,2,0,0,7,4,0,1,0,...,4,0,2,3,0,0,0,1,2,37
13815,123,361231504001,6,0,0,6,2,0,1,0,...,2,0,1,4,0,0,0,0,0,31
13816,123,361231504002,0,1,2,9,1,0,1,0,...,5,1,0,6,0,0,0,0,0,31
13817,123,361231504003,4,0,1,2,1,1,0,0,...,9,0,0,12,0,0,0,2,0,38
13818,123,361231504004,1,0,1,3,2,0,0,0,...,2,0,1,0,0,0,0,0,1,15
13819,123,361231505001,2,0,0,4,6,0,1,0,...,1,0,1,5,0,1,1,0,1,31
13820,123,361231505002,3,0,0,6,2,0,2,1,...,3,0,0,9,2,0,0,0,2,39
13821,123,361231505003,3,0,0,5,7,0,1,0,...,4,2,3,5,0,0,1,1,2,42
13822,123,361231505004,0,0,0,2,0,0,2,0,...,2,0,0,6,1,1,0,1,0,23

In [62]:
byCounty = analysis.groupby('countyCode')

In [63]:
ls = list(analysis.columns.values)

In [65]:
ls = ls[2:]

In [66]:
ls

['observed_Bladder',
 'observed_Bone',
 'observed_Brain',
 'observed_Breast',
 'observed_Colorectal',
 'observed_Esophagus',
 'observed_Kidney',
 'observed_Larynx',
 'observed_Leukemia',
 'observed_Liver',
 'observed_Lung',
 'observed_Mesothelioma',
 'observed_NHL',
 'observed_Nasal',
 'observed_Oral',
 'observed_Other',
 'observed_Ovary',
 'observed_Pancreas',
 'observed_Prostate',
 'observed_Soft_Tissue',
 'observed_Stomach',
 'observed_Testis',
 'observed_Thyroid',
 'observed_Uterus',
 'observed_Total']

In [68]:
for i in ls:
    print i, byCounty[i].aggregate(np.sum)

observed_Bladder countyCode
001     498
003      79
005     804
007     328
009     135
011     113
013     265
015     175
017      94
019     127
021     120
023      84
025      94
027     446
029    1786
031      72
033      79
035     111
037      90
039     107
041       9
043     135
045     160
047    2052
049      31
051     104
053     122
055    1087
057      95
059    2259
       ...
065     441
067     717
069     175
071     450
073      69
075     189
077     101
079     128
081    2186
083     243
085     654
087     394
089     182
091     372
093     259
095      51
097      23
099      68
101     164
103    2233
105     124
107      92
109     127
111     276
113     145
115     118
117     156
119    1269
121      98
123      42
Name: observed_Bladder, dtype: int64
observed_Bone countyCode
001     14
003      3
005     76
007      7
009      4
011      8
013      3
015      7
017      4
019      6
021      2
023      2
025      3
027     10
029     51
031      2
033      4
035      4
037      5
039      1
041      0
043      4
045      2
047    159
049      1
051      6
053      4
055     43
057      2
059     72
      ...
065      8
067     27
069      4
071     20
073      2
075      7
077      3
079      6
081    102
083      8
085     20
087     16
089      3
091      8
093      7
095      1
097      0
099      1
101      6
103     83
105      4
107      3
109      2
111      7
113      4
115      2
117      6
119     51
121      3
123      1
Name: observed_Bone, dtype: int64
observed_Brain countyCode
001    123
003     26
005    339
007     90
009     36
011     36
013     54
015     51
017     24
019     32
021     29
023     12
025     19
027    118
029    401
031     20
033     19
035     25
037     22
039     21
041      4
043     27
045     37
047    700
049      7
051     22
053     23
055    245
057     18
059    509
      ...
065     97
067    189
069     47
071    135
073     16
075     55
077     24
079     34
081    681
083     71
085    174
087    109
089     27
091     78
093     61
095      9
097     10
099     21
101     39
103    517
105     32
107     22
109     38
111     70
113     23
115     26
117     34
119    343
121     26
123     14
Name: observed_Brain, dtype: int64
observed_Breast countyCode
001    1190
003     176
005    3834
007     817
009     295
011     324
013     570
015     370
017     173
019     256
021     241
023     159
025     178
027    1211
029    4131
031     160
033     153
035     214
037     251
039     220
041      22
043     257
045     377
047    7330
049      96
051     255
053     269
055    3184
057     189
059    6320
       ...
065     888
067    1845
069     427
071    1253
073     175
075     395
077     234
079     427
081    7194
083     626
085    1788
087    1194
089     371
091     884
093     629
095      99
097      69
099     161
101     355
103    6053
105     280
107     208
109     314
111     750
113     300
115     269
117     344
119    4075
121     169
123     101
Name: observed_Breast, dtype: int64
observed_Colorectal countyCode
001     788
003     153
005    3004
007     666
009     279
011     217
013     382
015     268
017     156
019     232
021     195
023     131
025     165
027     759
029    2634
031     133
033     152
035     199
037     174
039     176
041      17
043     213
045     266
047    6181
049      78
051     179
053     205
055    1845
057     207
059    3746
       ...
065     685
067    1181
069     232
071     820
073     132
075     338
077     180
079     217
081    5523
083     456
085    1215
087     698
089     336
091     552
093     464
095     100
097      76
099      96
101     282
103    4002
105     198
107     147
109     197
111     562
113     173
115     148
117     265
119    2449
121     146
123      68
Name: observed_Colorectal, dtype: int64
observed_Esophagus countyCode
001    106
003     15
005    302
007     81
009     31
011     24
013     55
015     30
017     24
019     44
021     24
023     23
025     33
027     87
029    391
031     30
033     18
035     23
037     21
039     30
041      6
043     31
045     39
047    487
049      4
051     24
053     23
055    221
057     18
059    348
      ...
065     75
067    148
069     33
071     96
073     12
075     40
077     32
079     31
081    444
083     74
085    115
087     89
089     52
091     63
093     55
095     20
097      9
099     11
101     36
103    459
105     24
107     15
109     26
111     57
113     27
115     34
117     41
119    262
121     14
123      9
Name: observed_Esophagus, dtype: int64
observed_Kidney countyCode
001     275
003      39
005     846
007     188
009      80
011      87
013     136
015      80
017      52
019     107
021      60
023      30
025      46
027     244
029     909
031      39
033      42
035      71
037      62
039      42
041       4
043      82
045      79
047    1638
049      35
051      53
053      57
055     738
057      61
059    1450
       ...
065     253
067     434
069     101
071     322
073      41
075     136
077      66
079     103
081    1606
083     188
085     446
087     258
089      77
091     211
093     139
095      23
097      13
099      45
101      80
103    1476
105      73
107      62
109      50
111     164
113      66
115      67
117      78
119     810
121      49
123      32
Name: observed_Kidney, dtype: int64
observed_Larynx countyCode
001     67
003     12
005    293
007     52
009     28
011     26
013     34
015     33
017     13
019     27
021     15
023     11
025     16
027     61
029    259
031     11
033     23
035     16
037     15
039     15
041      3
043     10
045     20
047    436
049     11
051      7
053     20
055    162
057     17
059    259
      ...
065     71
067    110
069     19
071     74
073     13
075     41
077     14
079     22
081    399
083     62
085    122
087     45
089     37
091     56
093     36
095      7
097      5
099     11
101     29
103    311
105     24
107     18
109     12
111     44
113     24
115     17
117     23
119    179
121      4
123      7
Name: observed_Larynx, dtype: int64
observed_Leukemia countyCode
001     257
003      53
005     698
007     146
009      56
011      78
013     110
015      84
017      57
019      63
021      54
023      40
025      58
027     209
029     889
031      38
033      35
035      39
037      65
039      43
041       2
043      46
045      99
047    1352
049      39
051      49
053      54
055     608
057      42
059    1139
       ...
065     196
067     433
069      88
071     259
073      31
075     114
077      85
079      61
081    1267
083     133
085     353
087     235
089     101
091     170
093     147
095      29
097      18
099      39
101      74
103    1201
105      73
107      46
109      76
111     152
113      64
115      34
117      75
119     809
121      45
123      23
Name: observed_Leukemia, dtype: int64
observed_Liver countyCode
001     121
003      13
005     909
007      63
009      19
011      25
013      42
015      27
017      12
019      31
021      17
023      10
025       9
027     138
029     319
031      18
033      17
035      14
037      10
039      34
041       4
043      23
045      26
047    1113
049       8
051      22
053      21
055     273
057      15
059     532
       ...
065      85
067     172
069      29
071     136
073       6
075      26
077      13
079      36
081    1093
083      66
085     246
087      93
089      25
091      57
093      62
095      13
097       8
099       8
101      26
103     541
105      40
107      14
109      22
111      82
113      26
115      18
117      33
119     386
121      10
123       8
Name: observed_Liver, dtype: int64
observed_Lung countyCode
001    1333
003     207
005    3223
007     859
009     383
011     400
013     604
015     481
017     253
019     397
021     344
023     227
025     260
027    1085
029    4284
031     199
033     230
035     270
037     276
039     263
041      30
043     300
045     471
047    5911
049      93
051     264
053     329
055    2754
057     254
059    4871
       ...
065    1203
067    2143
069     467
071    1243
073     207
075     634
077     256
079     349
081    5815
083     783
085    1680
087     946
089     564
091     899
093     718
095     165
097      95
099     177
101     523
103    5870
105     357
107     225
109     268
111     758
113     359
115     350
117     395
119    3080
121     173
123     103
Name: observed_Lung, dtype: int64
observed_Mesothelioma countyCode
001    24
003     6
005    35
007    10
009     9
011     7
013     7
015     4
017     5
019     5
021     3
023     1
025     3
027    10
029    94
031     4
033     2
035     2
037     5
039     1
041     0
043     2
045     5
047    60
049     5
051     5
053     1
055    51
057     5
059    93
       ..
065    15
067    21
069     6
071    17
073     5
075    10
077     2
079     5
081    73
083    14
085    29
087    12
089    10
091    12
093    12
095     4
097     0
099     1
101     8
103    81
105     4
107     3
109     3
111    11
113     3
115     3
117    10
119    57
121     2
123     1
Name: observed_Mesothelioma, dtype: int64
observed_NHL countyCode
001     423
003      50
005    1264
007     254
009     107
011     110
013     166
015     129
017      54
019      87
021     100
023      54
025      67
027     317
029    1192
031      54
033      66
035      75
037      80
039      69
041       8
043      89
045     106
047    2302
049      39
051      68
053      79
055     905
057      61
059    1890
       ...
065     290
067     612
069     140
071     360
073      51
075     133
077      71
079     108
081    2102
083     213
085     545
087     387
089     139
091     267
093     220
095      42
097      17
099      53
101     109
103    1821
105      96
107      68
109      95
111     250
113     104
115      74
117     126
119    1254
121      42
123      49
Name: observed_NHL, dtype: int64
observed_Nasal countyCode
001    13
003     3
005    44
007     7
009     5
011     6
013     7
015     5
017     1
019     3
021     2
023     1
025     4
027     6
029    45
031     3
033     1
035     1
037     1
039     6
041     0
043     3
045     5
047    77
049     2
051     2
053     1
055    30
057     2
059    38
       ..
065     9
067    22
069     6
071    14
073     1
075     2
077     3
079     3
081    74
083     7
085    19
087    11
089     4
091     7
093     6
095     1
097     0
099     0
101     2
103    57
105     4
107     1
109     0
111     8
113     0
115     3
117     5
119    32
121     1
123     1
Name: observed_Nasal, dtype: int64
observed_Oral countyCode
001     194
003      42
005     700
007     141
009      52
011      54
013      86
015      59
017      46
019      39
021      54
023      29
025      34
027     145
029     634
031      27
033      32
035      53
037      40
039      41
041       2
043      46
045      67
047    1135
049      14
051      39
053      39
055     427
057      38
059     748
       ...
065     164
067     303
069      73
071     160
073      18
075      90
077      63
079      50
081    1001
083     106
085     223
087     116
089      75
091     155
093      91
095      24
097      18
099      24
101      70
103     843
105      53
107      30
109      45
111     126
113      59
115      42
117      52
119     510
121      26
123       9
Name: observed_Oral, dtype: int64
observed_Other countyCode
001    1187
003     190
005    3641
007     873
009     338
011     329
013     606
015     522
017     257
019     285
021     298
023     205
025     237
027    1015
029    4497
031     178
033     178
035     248
037     270
039     244
041      40
043     261
045     362
047    7350
049     114
051     213
053     257
055    2915
057     229
059    6011
       ...
065    1050
067    1824
069     457
071    1185
073     152
075     433
077     265
079     362
081    6544
083     661
085    1680
087    1026
089     470
091     856
093     660
095     141
097      84
099     132
101     418
103    6257
105     341
107     233
109     334
111     776
113     356
115     260
117     382
119    3753
121     184
123      95
Name: observed_Other, dtype: int64
observed_Ovary countyCode
001    100
003     17
005    427
007     92
009     39
011     32
013     62
015     57
017     28
019     30
021     27
023     22
025     20
027    108
029    398
031     17
033     14
035     24
037     33
039     25
041      3
043     25
045     44
047    826
049      9
051     31
053     20
055    281
057     17
059    664
      ...
065    111
067    202
069     59
071    135
073     29
075     34
077     23
079     39
081    829
083     60
085    176
087    118
089     34
091     88
093     43
095     20
097     11
099     12
101     38
103    625
105     33
107     20
109     30
111     85
113     32
115     26
117     36
119    410
121     24
123     11
Name: observed_Ovary, dtype: int64
observed_Pancreas countyCode
001     227
003      27
005     761
007     128
009      57
011      66
013     100
015      80
017      38
019      56
021      58
023      42
025      39
027     212
029     785
031      38
033      41
035      48
037      38
039      52
041       3
043      52
045      68
047    1565
049      37
051      26
053      50
055     576
057      49
059    1169
       ...
065     204
067     375
069      87
071     208
073      23
075      90
077      43
079      68
081    1435
083      96
085     357
087     199
089      66
091     160
093     128
095      31
097      12
099      33
101      69
103    1189
105      64
107      41
109      55
111     155
113      46
115      49
117      73
119     741
121      36
123      18
Name: observed_Pancreas, dtype: int64
observed_Prostate countyCode
001    1278
003     193
005    4573
007    1031
009     359
011     398
013     864
015     389
017     210
019     333
021     325
023     231
025     214
027    1014
029    4652
031     164
033     187
035     278
037     267
039     220
041      33
043     285
045     468
047    8215
049     120
051     274
053     434
055    3187
057     219
059    6281
       ...
065    1032
067    2441
069     473
071    1308
073     143
075     514
077     216
079     388
081    7830
083     729
085    1777
087    1484
089     459
091     922
093     554
095     115
097      83
099     144
101     383
103    6321
105     325
107     218
109     419
111     723
113     377
115     319
117     464
119    4165
121     227
123      98
Name: observed_Prostate, dtype: int64
observed_Soft_Tissue countyCode
001     57
003      9
005    196
007     32
009     21
011     17
013     23
015     13
017     12
019     15
021     10
023      6
025      7
027     48
029    177
031      7
033      8
035      9
037      7
039      6
041      1
043      4
045     28
047    381
049      6
051     11
053     12
055    137
057     12
059    280
      ...
065     41
067     82
069     14
071     56
073      8
075     16
077     16
079     33
081    351
083     25
085     78
087     62
089     16
091     35
093     28
095      8
097      3
099      5
101     15
103    311
105     10
107      5
109      8
111     40
113     12
115     12
117     11
119    188
121      8
123     10
Name: observed_Soft_Tissue, dtype: int64
observed_Stomach countyCode
001     116
003      21
005     693
007      93
009      34
011      36
013      54
015      40
017      15
019      34
021      31
023      15
025      20
027     113
029     396
031      18
033      10
035      19
037      27
039      24
041       3
043      26
045      31
047    1546
049      13
051      20
053      26
055     325
057      27
059     585
       ...
065     109
067     162
069      38
071     117
073      17
075      32
077      18
079      45
081    1452
083      56
085     221
087     149
089      35
091      79
093      71
095      19
097       3
099      13
101      34
103     605
105      39
107      16
109      26
111      56
113      27
115      27
117      34
119     453
121      15
123       6
Name: observed_Stomach, dtype: int64
observed_Testis countyCode
001     43
003      4
005    117
007     25
009     17
011     11
013     14
015      9
017      9
019     14
021     15
023      6
025      5
027     46
029    145
031      4
033      4
035      9
037      6
039     14
041      0
043      8
045     28
047    265
049      2
051      9
053     14
055     99
057     11
059    203
      ...
065     37
067     76
069     21
071     69
073      6
075     17
077     12
079     15
081    226
083     25
085     75
087     52
089     19
091     48
093     25
095      7
097      4
099      5
101     15
103    236
105      8
107     11
109     19
111     30
113      8
115     17
117     15
119    128
121      6
123      2
Name: observed_Testis, dtype: int64
observed_Thyroid countyCode
001     212
003      19
005     634
007     203
009      37
011      58
013      75
015      75
017      43
019      40
021      33
023      29
025      35
027     239
029     702
031      27
033      28
035      51
037      25
039      39
041       4
043      55
045      55
047    1919
049      16
051      31
053      56
055     446
057      36
059    1272
       ...
065     207
067     331
069      66
071     373
073      25
075      84
077      45
079     113
081    1559
083     129
085     606
087     282
089      42
091     173
093      84
095      22
097      17
099      18
101      44
103    1439
105      73
107      40
109      61
111     148
113      48
115      62
117      40
119     873
121      28
123      14
Name: observed_Thyroid, dtype: int64
observed_Uterus countyCode
001     231
003      32
005    1025
007     212
009      71
011      67
013     149
015      85
017      57
019      60
021      66
023      54
025      47
027     309
029     868
031      51
033      42
035      59
037      63
039      52
041       3
043      69
045      75
047    2110
049      28
051      47
053      51
055     698
057      58
059    1423
       ...
065     193
067     414
069      91
071     267
073      36
075     109
077      76
079      88
081    1848
083     163
085     444
087     288
089     105
091     149
093     150
095      35
097      19
099      40
101      84
103    1332
105      82
107      41
109      91
111     185
113      91
115      71
117      68
119     894
121      33
123      31
Name: observed_Uterus, dtype: int64
observed_Total countyCode
001     8877
003     1389
005    28438
007     6398
009     2492
011     2529
013     4468
015     3073
017     1637
019     2323
021     2123
023     1424
025     1613
027     7950
029    30639
031     1314
033     1385
035     1862
037     1853
039     1745
041      201
043     2053
045     2918
047    55110
049      808
051     1761
053     2167
055    21237
057     1682
059    42162
       ...
065     7464
067    14264
069     3153
071     9077
073     1218
075     3539
077     1861
079     2731
081    51634
083     4994
085    13043
087     8263
089     3249
091     6301
093     4649
095      986
097      597
099     1118
101     2903
103    43863
105     2361
107     1579
109     2318
111     5515
113     2374
115     2048
117     2766
119    27171
121     1369
123      753
Name: observed_Total, dtype: int64

In [69]:
aggr = pd.DataFrame()

In [70]:
aggr

Empty DataFrame
Columns: []
Index: []

In [71]:
for i in ls:
    aggr[i] = byCounty[i].aggregate(np.sum)

In [72]:
aggr

,observed_Bladder,observed_Bone,observed_Brain,observed_Breast,observed_Colorectal,observed_Esophagus,observed_Kidney,observed_Larynx,observed_Leukemia,observed_Liver,...,observed_Other,observed_Ovary,observed_Pancreas,observed_Prostate,observed_Soft_Tissue,observed_Stomach,observed_Testis,observed_Thyroid,observed_Uterus,observed_Total
countyCode,,,,,,,,,,,,,,,,,,,,,
001,498,14,123,1190,788,106,275,67,257,121,...,1187,100,227,1278,57,116,43,212,231,8877
003,79,3,26,176,153,15,39,12,53,13,...,190,17,27,193,9,21,4,19,32,1389
005,804,76,339,3834,3004,302,846,293,698,909,...,3641,427,761,4573,196,693,117,634,1025,28438
007,328,7,90,817,666,81,188,52,146,63,...,873,92,128,1031,32,93,25,203,212,6398
009,135,4,36,295,279,31,80,28,56,19,...,338,39,57,359,21,34,17,37,71,2492
011,113,8,36,324,217,24,87,26,78,25,...,329,32,66,398,17,36,11,58,67,2529
013,265,3,54,570,382,55,136,34,110,42,...,606,62,100,864,23,54,14,75,149,4468
015,175,7,51,370,268,30,80,33,84,27,...,522,57,80,389,13,40,9,75,85,3073
017,94,4,24,173,156,24,52,13,57,12,...,257,28,38,210,12,15,9,43,57,1637
019,127,6,32,256,232,44,107,27,63,31,...,285,30,56,333,15,34,14,40,60,2323
021,120,2,29,241,195,24,60,15,54,17,...,298,27,58,325,10,31,15,33,66,2123
023,84,2,12,159,131,23,30,11,40,10,...,205,22,42,231,6,15,6,29,54,1424
025,94,3,19,178,165,33,46,16,58,9,...,237,20,39,214,7,20,5,35,47,1613
027,446,10,118,1211,759,87,244,61,209,138,...,1015,108,212,1014,48,113,46,239,309,7950
029,1786,51,401,4131,2634,391,909,259,889,319,...,4497,398,785,4652,177,396,145,702,868,30639
031,72,2,20,160,133,30,39,11,38,18,...,178,17,38,164,7,18,4,27,51,1314
033,79,4,19,153,152,18,42,23,35,17,...,178,14,41,187,8,10,4,28,42,1385
035,111,4,25,214,199,23,71,16,39,14,...,248,24,48,278,9,19,9,51,59,1862
037,90,5,22,251,174,21,62,15,65,10,...,270,33,38,267,7,27,6,25,63,1853
039,107,1,21,220,176,30,42,15,43,34,...,244,25,52,220,6,24,14,39,52,1745
041,9,0,4,22,17,6,4,3,2,4,...,40,3,3,33,1,3,0,4,3,201
043,135,4,27,257,213,31,82,10,46,23,...,261,25,52,285,4,26,8,55,69,2053
045,160,2,37,377,266,39,79,20,99,26,...,362,44,68,468,28,31,28,55,75,2918
047,2052,159,700,7330,6181,487,1638,436,1352,1113,...,7350,826,1565,8215,381,1546,265,1919,2110,55110
049,31,1,7,96,78,4,35,11,39,8,...,114,9,37,120,6,13,2,16,28,808
051,104,6,22,255,179,24,53,7,49,22,...,213,31,26,274,11,20,9,31,47,1761
053,122,4,23,269,205,23,57,20,54,21,...,257,20,50,434,12,26,14,56,51,2167
055,1087,43,245,3184,1845,221,738,162,608,273,...,2915,281,576,3187,137,325,99,446,698,21237
057,95,2,18,189,207,18,61,17,42,15,...,229,17,49,219,12,27,11,36,58,1682
059,2259,72,509,6320,3746,348,1450,259,1139,532,...,6011,664,1169,6281,280,585,203,1272,1423,42162
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
065,441,8,97,888,685,75,253,71,196,85,...,1050,111,204,1032,41,109,37,207,193,7464
067,717,27,189,1845,1181,148,434,110,433,172,...,1824,202,375,2441,82,162,76,331,414,14264
069,175,4,47,427,232,33,101,19,88,29,...,457,59,87,473,14,38,21,66,91,3153
071,450,20,135,1253,820,96,322,74,259,136,...,1185,135,208,1308,56,117,69,373,267,9077
073,69,2,16,175,132,12,41,13,31,6,...,152,29,23,143,8,17,6,25,36,1218
075,189,7,55,395,338,40,136,41,114,26,...,433,34,90,514,16,32,17,84,109,3539
077,101,3,24,234,180,32,66,14,85,13,...,265,23,43,216,16,18,12,45,76,1861
079,128,6,34,427,217,31,103,22,61,36,...,362,39,68,388,33,45,15,113,88,2731
081,2186,102,681,7194,5523,444,1606,399,1267,1093,...,6544,829,1435,7830,351,1452,226,1559,1848,51634
083,243,8,71,626,456,74,188,62,133,66,...,661,60,96,729,25,56,25,129,163,4994
085,654,20,174,1788,1215,115,446,122,353,246,...,1680,176,357,1777,78,221,75,606,444,13043
087,394,16,109,1194,698,89,258,45,235,93,...,1026,118,199,1484,62,149,52,282,288,8263
089,182,3,27,371,336,52,77,37,101,25,...,470,34,66,459,16,35,19,42,105,3249
091,372,8,78,884,552,63,211,56,170,57,...,856,88,160,922,35,79,48,173,149,6301
093,259,7,61,629,464,55,139,36,147,62,...,660,43,128,554,28,71,25,84,150,4649
095,51,1,9,99,100,20,23,7,29,13,...,141,20,31,115,8,19,7,22,35,986
097,23,0,10,69,76,9,13,5,18,8,...,84,11,12,83,3,3,4,17,19,597
099,68,1,21,161,96,11,45,11,39,8,...,132,12,33,144,5,13,5,18,40,1118
101,164,6,39,355,282,36,80,29,74,26,...,418,38,69,383,15,34,15,44,84,2903
103,2233,83,517,6053,4002,459,1476,311,1201,541,...,6257,625,1189,6321,311,605,236,1439,1332,43863
105,124,4,32,280,198,24,73,24,73,40,...,341,33,64,325,10,39,8,73,82,2361
107,92,3,22,208,147,15,62,18,46,14,...,233,20,41,218,5,16,11,40,41,1579
109,127,2,38,314,197,26,50,12,76,22,...,334,30,55,419,8,26,19,61,91,2318
111,276,7,70,750,562,57,164,44,152,82,...,776,85,155,723,40,56,30,148,185,5515
113,145,4,23,300,173,27,66,24,64,26,...,356,32,46,377,12,27,8,48,91,2374
115,118,2,26,269,148,34,67,17,34,18,...,260,26,49,319,12,27,17,62,71,2048
117,156,6,34,344,265,41,78,23,75,33,...,382,36,73,464,11,34,15,40,68,2766
119,1269,51,343,4075,2449,262,810,179,809,386,...,3753,410,741,4165,188,453,128,873,894,27171
121,98,3,26,169,146,14,49,4,45,10,...,184,24,36,227,8,15,6,28,33,1369
123,42,1,14,101,68,9,32,7,23,8,...,95,11,18,98,10,6,2,14,31,753